### ISSUE TITLE
不支持decimal ？

### ISSUE THREAD

**Issue by jilieryuyi** [fengxiangyun/php-mysql-replication#1]
RowEvent.php并没有对decimal进行处理！

**Comment by fengxiangyun** [comment]
目前已经增加对 NEWDECIMAL的支持，还有少部分暂时不支持 ，需要请反馈

**Comment by jilieryuyi** [comment]
赞一个，测试正常！

**Comment by jilieryuyi** [comment]
请教个问题：https://segmentfault.com/q/1010000011204046
